application: gcdc2013-tourbly
version: 1
runtime: python27
api_version: 1
threadsafe: yes

error_handlers:
- error_code: over_quota
  file: over_quota.html

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets

- url: .*
  script: tourbly.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest


